# Openseespy-issue
To ask openseespy doubts
ARNING: system ndm and ndf are zero
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\tonmo\.spyder-py3\temp.py:30
    op.node(1,0,0)

OpenSeesError: See stderr output

How to resolve this??
